name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: 7.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.4
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/standardrb

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
           - 3.2.6
           - 3.3.4
        rails:
            - '7.1'
            - '7.2'
            - '8.0'
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rspec
